# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  # username: main
  # password:
  # host: localhost

development:
  <<: *default
  database: maino_blog

test:
  <<: *default
  database: maino_blog

production:
  <<: *default
  database: maino_blog
